### ISSUE TITLE
[RoadMap] Mooncake Roadmap Q1 & Q2 2025

### ISSUE THREAD

**Issue by stmatengss** [kvcache-ai/Mooncake#44]
We categorized our roadmap into two major themes: New Component (Mooncake Managed Object Store) and New Features of Mooncake. As we are seeing more.

-------

####  25Q1
* Object Store Interfaces
    - [ ] vLLM adapter for PUT/GET interface
        - [ ] Multiple Language support
    - [ ] Prefix KVCache Management
* Object Store Features
    - [ ] Support M-to-N (XpYd) KVCache Sharing between P/D instances
        - [ ] Support building multiple connections between Xp and Yd
        - [ ] Object Store Master to manage metadata of KVcache
        - [ ] Asynchronous KV cache transfer with Layer-by-layer pipeline

#### 25Q2+
* Advanced Features
    - [ ] Cluster reconfiguration
    - [ ] Better cache eviction strategy
    - [ ] Multi-tier caching 

#### Transfer Engine
* 25Q1
    - [ ] Revise APIs to support more protocols/media
    - [ ] Check & revise error handling (problems from device/connection/software)
    - [ ] Metadata Management and OOB Communication
        - [ ] Plugin-based metadata client (etcd, Redis, HTTP, ...)
        - [ ] Extend current's naive handshake mechanism
    - [ ] Add support of transports
        - [ ] CXL/Shared memory
        - [ ] NVMe-of
* 25Q2+
    - [ ] Transfer data from GPU memory
        - [ ] More features integrated into GDS, including direct RDMA-based VRAM-to-DRAM transfers
        - [ ] VRAM-to-VRAM fast transfers based on NVLink
        - [ ] Support for GPU of other vendors (domestic...)
    - [ ] Path Selection
        - [ ] Automatically generate Topology Matrix according to hardware conditions
        - [ ] Optimize multi-NIC scheduling strategy based on request load and hardware characteristics
    - [ ] Performance
        - [ ] Working-set based QP management, avoiding RNIC cache thrashing
    - [ ] Security Enhancement
        - [ ] Remote memory protection based on RDMA keys
        - [ ] Auth

#### P2P Store
* 25Q1
    - [ ] Support python interface
    - [ ] Network bandwidth allocation

#### LLM Framework Integration
* 25Q1
    - [ ] ZeroCopy from vLLM to RDMA memory
    - [ ] Support More LLM Framework
        - [ ] TensorRT-LLM
    - [ ] Support Asynchronous KV cache transfer for vLLM
        - [ ] Layer-by-layer pipeline
        - [ ] API: transferAsync in class VLLMAdaptor
    - [ ] Support KVCache Prefetch
 -----------
If any of the items you wanted is not on the roadmap, your suggestion and contribution are still welcomed! Please feel free to comment in this thread, open feature request, or create an RFC.

**Comment by VegetaPn** [comment]
The roadmap looks fantastic! What does "Cluster reconfiguration" mean? Does it refer to dynamically adjusting the P/D role type?

**Comment by ziqianliu423** [comment]
Hello, I am interested in the Transport support CXL/shared memory and maybe I can do this in one month.

**Comment by stmatengss** [comment]
> The roadmap looks fantastic! What does "Cluster reconfiguration" mean? Does it refer to dynamically adjusting the P/D role type?

Yes, it has two meanings. Firstly, any GPU server can freely join or leave the Mooncake KVCache pool. Secondly, a Prefill or Decoding Instance can change its role type.

**Comment by stmatengss** [comment]
> Hello, I am interested in the Transport support CXL/shared memory and maybe I can do this in one month.

Thank you for your contribution. I look forward to seeing the pull request on GitHub.

**Comment by doujiang24** [comment]
`Check & revise error handling (problems from device/connection/software)`
Hello, I'm happy to take this one in Q1.

**Comment by alogfans** [comment]
> `Check & revise error handling (problems from device/connection/software)`
> Hello, I'm happy to take this one in Q1.

Thank you for your contribution! Looking forward to seeing the pull request on GitHub.

**Comment by ANormalMan12** [comment]
I think it quite hard to implement "ZeroCopy from vLLM to RDMA memory" and "Layer-by-layer pipeline" without modifying core components of vllm a lot. Is there an easier way to implement "ZeroCopy" and "Layer-by-layer Pipeline"?

**Comment by cherhh** [comment]
Is the functionality provided by this Mooncake Managed Object Store similar to that of an in-memory database like Redis?

**Comment by ZhaiFeiyue** [comment]
is there any guide/doc for how to run XPYD on vllm with mooncake trasnfer engine?

**Comment by stmatengss** [comment]
> is there any guide/doc for how to run XPYD on vllm with mooncake trasnfer engine?

Thanks for your interest! FYI: https://github.com/vllm-project/vllm/pull/12957

**Comment by ZhaiFeiyue** [comment]
> > is there any guide/doc for how to run XPYD on vllm with mooncake trasnfer engine?
> 
> Thanks for your interest! FYI: [vllm-project/vllm#12957](https://github.com/vllm-project/vllm/pull/12957)

thanks @stmatengss I have reproduced vllm with Mooncake (xpyd feature)

**Comment by Huixxi** [comment]
I saw there is a pr for supporting sglang https://github.com/sgl-project/sglang/pull/4880, is there a demo to run for test?

**Comment by maobaolong** [comment]
offload vllm kvcache supported is necessary

**Comment by stmatengss** [comment]
> offload vllm kvcache supported is necessary

Sure. We are working on kvcache offloading such as SSD. If you are interested, we are happy to collaborate.

**Comment by kiwi3shark** [comment]
Appreciate the amazing work! I just wonder would it be possible to have a Python interface for the transfer engine since there is a Rust binding implemented already. A neat Python binding would be helpful for the transfer engine to be incorporated into a bunch of Python-first ecosystems like Ray.

**Comment by stmatengss** [comment]
> Appreciate the amazing work! I just wonder would it be possible to have a Python interface for the transfer engine since there is a Rust binding implemented already. A neat Python binding would be helpful for the transfer engine to be incorporated into a bunch of Python-first ecosystems like Ray.

Thank you for your interest. There are already several Python interfaces for the transfer engine here (https://github.com/kvcache-ai/Mooncake/blob/main/mooncake-integration/transfer_engine/transfer_engine_py.cpp). Sorry for omitting the related documents.
